import { apiClient } from "@/lib/api/client";

export interface PomodoroSettings {
  userId: string;
  workDuration: number;
  shortBreakDuration: number;
  longBreakDuration: number;
  longBreakInterval: number;
  autoStartNext: boolean;
}

export interface UpdatePomodoroSettingsRequest {
  workDuration: number;
  shortBreakDuration: number;
  longBreakDuration: number;
  longBreakInterval: number;
  autoStartNext: boolean;
}

export interface StartSessionRequest {
  type: number; // 1: Pomodoro, 2: Short Break, 3: Long Break
}

export interface SessionResponse {
  id: string;
  userId: string;
  type: string; // "Work" | "ShortBreak" | "LongBreak"
  status: string; // "Active" | "Completed" | "Skipped" | "Incomplete"
  start: string;
  end: string;
  duration: string;
  cycleIndex: number;
  isAutoGenerated: boolean;
}

export interface ApiResponse<T> {
  data: T;
  success: boolean;
  message: string;
  errors: unknown;
  errorType: number;
}

export interface SessionHistoryItem {
  id: string;
  userId: string;
  type: string; // "Work" | "ShortBreak" | "LongBreak"
  status: string; // "Active" | "Completed" | "Skipped" | "Incomplete"
  start: string;
  end: string;
  duration: string;
  cycleIndex: number;
  isAutoGenerated: boolean;
}

export interface SessionHistoryData {
  sessions: SessionHistoryItem[];
  totalCount: number;
  totalFocusMinutes: number;
  totalBreakMinutes: number;
  averageFocusDuration: number;
  completionRate: number;
}

export interface SessionHistoryResponse {
  totalCount: number;
  page: number;
  pageSize: number;
  data: SessionHistoryData[];
  success: boolean;
  message: string;
  errors: unknown;
  errorType: number;
}

class PomodoroService {
  /**
   * Get user's Pomodoro settings
   * @param userId - User ID
   */
  async getSettings(userId: string): Promise<PomodoroSettings> {
    try {
      const response = await apiClient.get<PomodoroSettings>(
        `/users/${userId}/pomodoro/settings`
      );
      return response.data;
    } catch (error) {
      console.error("[PomodoroService] Error fetching settings:", error);
      // Return default settings if fetch fails
      return {
        userId,
        workDuration: 25,
        shortBreakDuration: 5,
        longBreakDuration: 15,
        longBreakInterval: 4,
        autoStartNext: false,
      };
    }
  }

  /**
   * Update user's Pomodoro settings
   * @param userId - User ID
   * @param settings - Updated settings
   * @returns Success message or throws error
   */
  async updateSettings(
    userId: string,
    settings: UpdatePomodoroSettingsRequest
  ): Promise<void> {
    try {
      // Validate settings before sending
      if (
        !settings.workDuration ||
        settings.workDuration < 15 ||
        settings.workDuration > 180
      ) {
        throw new Error("Invalid workDuration");
      }
      if (
        !settings.shortBreakDuration ||
        settings.shortBreakDuration < 5 ||
        settings.shortBreakDuration > 60
      ) {
        throw new Error("Invalid shortBreakDuration");
      }
      if (
        !settings.longBreakDuration ||
        settings.longBreakDuration < 10 ||
        settings.longBreakDuration > 120
      ) {
        throw new Error("Invalid longBreakDuration");
      }
      if (
        !settings.longBreakInterval ||
        settings.longBreakInterval < 2 ||
        settings.longBreakInterval > 10
      ) {
        throw new Error("Invalid longBreakInterval");
      }

      await apiClient.put<string>(
        `/users/${userId}/pomodoro/settings`,
        settings
      );
    } catch (error) {
      console.error("[PomodoroService] Error updating settings:", error);
      throw error;
    }
  }

  /**
   * Start a new Pomodoro session
   * @param userId - User ID
   * @param type - Session type (1: Work, 2: Short Break, 3: Long Break)
   */
  async startSession(userId: string, type: number): Promise<SessionResponse> {
    try {
      // Send type as raw number in body, not wrapped in object
      // apiClient returns APIResponse<T>, so we access response.data to get T
      const response = await apiClient.post<SessionResponse>(
        `/users/${userId}/pomodoro/sessions`,
        type
      );
      return response.data;
    } catch (error) {
      console.error("[PomodoroService] Error starting session:", error);
      throw error;
    }
  }

  /**
   * Complete the current Pomodoro session
   * Backend automatically creates next session if autoStartNext is enabled
   * @param userId - User ID
   */
  async completeSession(userId: string): Promise<SessionResponse | null> {
    try {
      const response = await apiClient.post<SessionResponse>(
        `/users/${userId}/pomodoro/sessions/complete`,
        {}
      );
      // Return the new session data if backend auto-created one
      return response.data;
    } catch (error) {
      console.error("[PomodoroService] Error completing session:", error);
      throw error;
    }
  }

  /**
   * Skip the current Pomodoro session
   * Backend automatically creates next session if autoStartNext is enabled
   * @param userId - User ID
   */
  async skipSession(userId: string): Promise<SessionResponse | null> {
    try {
      const response = await apiClient.post<SessionResponse>(
        `/users/${userId}/pomodoro/sessions/skip`,
        {}
      );
      // Return the new session data if backend auto-created one
      return response.data;
    } catch (error) {
      console.error("[PomodoroService] Error skipping session:", error);
      throw error;
    }
  }

  /**
   * Get session history with statistics
   * @param userId - User ID
   * @param page - Page number (default: 1)
   * @param pageSize - Page size (default: 10)
   */
  async getSessionHistory(
    userId: string,
    page: number = 1,
    pageSize: number = 10
  ): Promise<SessionHistoryResponse> {
    try {
      const response = await apiClient.get<SessionHistoryResponse>(
        `/users/${userId}/pomodoro/sessions/history?page=${page}&pageSize=${pageSize}`
      );
      return response.data;
    } catch (error) {
      console.error("[PomodoroService] Error fetching session history:", error);
      throw error;
    }
  }
}

const pomodoroService = new PomodoroService();
export default pomodoroService;
